git:
  paging:
    colorArg: never
    pager: delta --dark --paging=never
commandLog:
  fileDiffCommand: "git diff --color=always {{parentSha}} {{targetSha}} -- {{filepath}} | delta --paging=never"
os:
  editPreset: "nvim-remote"
